package compdiff_test

import (
	"fmt"
	"os"
	"testing"

	"github.com/yoanm/go-composer-diff"
	"github.com/yoanm/go-deps-diff/contract"
	"github.com/yoanm/go-deps-diff/contract/semver"
	difftesting "github.com/yoanm/go-deps-diff/testing"
)

func TestIntegration_SimpleFixtures(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		reqFilePath  string
		lockFilePath string
		expected     contract.PackageMap
	}{
		{
			name:         "Simple",
			reqFilePath:  "./testdata/composer-simple.json",
			lockFilePath: "./testdata/composer-simple.lock",
			expected:     integrationSimpleFixturesSimpleCaseExpectation,
		},
		{
			name:         "Complex",
			reqFilePath:  "./testdata/composer-complex.json",
			lockFilePath: "./testdata/composer-complex.lock",
			expected:     integrationSimpleFixturesComplexCaseExpectation,
		},
	}
	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			myMap, err := buildMapFromFixtures(testCase)
			if err != nil {
				t.Fatal(err)
			}

			for _, err := range difftesting.ValidatePackageMap(*myMap, testCase.expected) {
				t.Error(err)
			}
		})
	}
}

func buildMapFromFixtures(testCase struct {
	name         string
	reqFilePath  string
	lockFilePath string
	expected     contract.PackageMap
},
) (*contract.PackageMap, error) {
	// Load fixture files
	simpleReq, err := os.ReadFile(testCase.reqFilePath)
	if err != nil {
		return nil, fmt.Errorf("error while reading requirement file = %w", err)
	}

	simpleLock, err := os.ReadFile(testCase.lockFilePath)
	if err != nil {
		return nil, fmt.Errorf("error while reading lock file = %w", err)
	}

	myMap, err := compdiff.BuildMapFromBytes(simpleReq, simpleLock)
	if err != nil {
		return nil, fmt.Errorf("error while building map = %w", err)
	}

	return &myMap, nil
}

var integrationSimpleFixturesSimpleCaseExpectation = map[string]contract.PkgWrapper{
	"vendor/package-a": &difftesting.TestPkgWrapper{
		Name:               "vendor/package-a",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.3", Label: "1.2.3", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 3, Extra: ""}},
		Link:               "https://example.com/wiki/package-a",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/package-b": &difftesting.TestPkgWrapper{
		Name:               "vendor/package-b",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v2.0.0", Label: "v2.0.0", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/wiki/package-b",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/package-c": &difftesting.TestPkgWrapper{
		Name:               "vendor/package-c",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.5.1", Label: "3.5.1", Semver: &semver.Version{Major: 3, Minor: 5, Patch: 1, Extra: ""}},
		Link:               "https://example.com/package-c",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/package-dev-a": &difftesting.TestPkgWrapper{
		Name:               "vendor/package-dev-a",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://github.com/vendor/package-dev-a",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/package-dev-b": &difftesting.TestPkgWrapper{
		Name:               "vendor/package-dev-b",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v1.1.0", Label: "v1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://github.com/vendor/package-dev-b",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
}

var integrationSimpleFixturesComplexCaseExpectation = map[string]contract.PkgWrapper{
	"vendor/pkg-0001": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0001",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0001",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0002": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0002",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0002",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0003": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0003",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0003",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0004": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0004",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0004",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0005": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0005",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1-beta.2", Label: "2.2.1-beta.2", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: "-beta.2"}},
		Link:               "https://example.com/support-docs/vendor/pkg-0005",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0006": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0006",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0006",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0007": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0007",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v3.3.1", Label: "v3.3.1", Semver: &semver.Version{Major: 3, Minor: 3, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0007",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0008": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0008",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0008",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0009": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0009",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0009",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0010": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0010",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "86f73d4043691e3b47499100a436fec5ea150a2a",
			Label:  "dev-master#86f73d4",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0010",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0011": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0011",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0012": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0012",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0012",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0013": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0013",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0013",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0014": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0014",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v5.2.2", Label: "v5.2.2", Semver: &semver.Version{Major: 5, Minor: 2, Patch: 2, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0014",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0015": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0015",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1-beta.0", Label: "4.0.1-beta.0", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: "-beta.0"}},
		Link:               "https://example.com/support-docs/vendor/pkg-0015",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0016": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0016",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0016",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0017": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0017",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0017",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0018": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0018",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0018",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0019": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0019",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0019",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0020": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0020",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "6063a199b704577d953310b513f3011743943b5e",
			Label:  "dev-feature/main#6063a19",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0020",
		DevOnly:            false,
		RootRequirement:    true,
		RootDevRequirement: false,
	},
	"vendor/pkg-0021": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0021",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v2.1.0", Label: "v2.1.0", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0021",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0022": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0022",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0023": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0023",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0023",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0024": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0024",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0024",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0025": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0025",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1-beta.1", Label: "2.1.1-beta.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: "-beta.1"}},
		Link:               "https://example.com/support-docs/vendor/pkg-0025",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0026": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0026",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0026",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0027": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0027",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0027",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0028": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0028",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v4.0.1", Label: "v4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0028",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0029": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0029",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0029",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0030": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0030",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "b8a56915c984281cdd1dc902cacbbaa0c7c81c36",
			Label:  "2.9.x-dev#b8a5691",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0030",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0031": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0031",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0031",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0032": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0032",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0032",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0033": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0033",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0034": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0034",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0034",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0035": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0035",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v1.3.2", Label: "v1.3.2", Semver: &semver.Version{Major: 1, Minor: 3, Patch: 2, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0035",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0036": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0036",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0036",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0037": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0037",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0037",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0038": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0038",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0038",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0039": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0039",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0039",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0040": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0040",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "5695761b4841b1e8bc57429ada7d895fdd548051",
			Label:  "dev-main#5695761",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0040",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0041": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0041",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0041",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0042": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0042",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v3.2.0", Label: "v3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0042",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0043": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0043",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0043",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0044": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0044",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0045": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0045",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1-beta.0", Label: "2.0.1-beta.0", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: "-beta.0"}},
		Link:               "https://example.com/support-docs/vendor/pkg-0045",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0046": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0046",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0046",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0047": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0047",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0047",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0048": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0048",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0048",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0049": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0049",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v5.1.1", Label: "v5.1.1", Semver: &semver.Version{Major: 5, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0049",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0050": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0050",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "7e95d646be53792e94a15b5413916b39ab5c8f58",
			Label:  "dev-master#7e95d64",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0050",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0051": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0051",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0051",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0052": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0052",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0052",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0053": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0053",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0053",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0054": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0054",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0054",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0055": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0055",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1-beta.1", Label: "4.1.1-beta.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: "-beta.1"}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0056": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0056",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v2.0.2", Label: "v2.0.2", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 2, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0056",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0057": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0057",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0057",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0058": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0058",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0058",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0059": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0059",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0059",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0060": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0060",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "0e11ad96f8820b9230f093b0f7db8e8017bd9a97",
			Label:  "3.1.x-dev#0e11ad9",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0060",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0061": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0061",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0061",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0062": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0062",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0062",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0063": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0063",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v4.3.0", Label: "v4.3.0", Semver: &semver.Version{Major: 4, Minor: 3, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0063",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0064": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0064",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0064",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0065": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0065",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "2.2.1-beta.2", Label: "2.2.1-beta.2", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: "-beta.2"}},
		Link:               "https://example.com/support-source/vendor/pkg-0065",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0066": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0066",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0067": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0067",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0067",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0068": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0068",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0068",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0069": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0069",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0069",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0070": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0070",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "1abd40fc0f178273874183910b1203ac6867db2c",
			Label:  "dev-feature/awesome-feature#1abd40f",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0070",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0071": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0071",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0071",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0072": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0072",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0072",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0073": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0073",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0073",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0074": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0074",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0074",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0075": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0075",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1-beta.0", Label: "4.0.1-beta.0", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: "-beta.0"}},
		Link:               "https://example.com/support-source/vendor/pkg-0075",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0076": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0076",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0076",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0077": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0077",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v3.1.2", Label: "v3.1.2", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 2, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0078": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0078",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0078",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0079": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0079",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0079",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0080": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0080",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "4599bc2a13ed6bcc3aa8a96e0e4c54174f8be802",
			Label:  "2.1.x-dev#4599bc2",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0080",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0081": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0081",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0081",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0082": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0082",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0082",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0083": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0083",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0083",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0084": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0084",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v5.0.0", Label: "v5.0.0", Semver: &semver.Version{Major: 5, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0084",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0085": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0085",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1-beta.1", Label: "2.1.1-beta.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: "-beta.1"}},
		Link:               "https://example.com/support-source/vendor/pkg-0085",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0086": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0086",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0086",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0087": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0087",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0087",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0088": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0088",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://github.com/example/homepage/vendor/pkg-0088",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0089": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0089",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0089",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0090": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0090",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "e643d0fa6e8b0a92f19ecce35b77de2d9f9bd749",
			Label:  "dev-master#e643d0f",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0090",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0091": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0091",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "v2.3.1", Label: "v2.3.1", Semver: &semver.Version{Major: 2, Minor: 3, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0091",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0092": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0092",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0092",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0093": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0093",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0093",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0094": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0094",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0094",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0095": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0095",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1-beta.2", Label: "4.2.1-beta.2", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: "-beta.2"}},
		Link:               "https://example.com/support-source/vendor/pkg-0095",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0096": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0096",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0096",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0097": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0097",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0097",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0098": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0098",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v4.2.2", Label: "v4.2.2", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 2, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0098",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0099": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0099",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0100": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0100",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "f72ac1c48716475182f43a1abcafd368791fa11b",
			Label:  "dev-master#f72ac1c",
			Semver: nil,
		},
		Link:               "https://example.com/support-wiki/vendor/pkg-0100",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0101": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0101",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0101",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0102": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0102",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0102",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0103": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0103",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0103",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0104": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0104",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0104",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0105": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0105",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v1.1.0", Label: "v1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0105",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0106": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0106",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0106",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0107": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0107",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0107",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0108": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0108",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0108",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0109": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0109",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0109",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0110": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0110",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "e51d682ae5e7d39ffef508f906b4428249476547",
			Label:  "1.2.x-dev#e51d682",
			Semver: nil,
		},
		Link:               "",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: true,
	},
	"vendor/pkg-0111": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0111",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0111",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0112": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0112",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v3.0.1", Label: "v3.0.1", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0112",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0113": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0113",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0113",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0114": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0114",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0114",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0115": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0115",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1-beta.1", Label: "4.1.1-beta.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: "-beta.1"}},
		Link:               "https://example.com/support-source/vendor/pkg-0115",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0116": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0116",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0116",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0117": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0117",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0117",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0118": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0118",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0118",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0119": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0119",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v5.3.2", Label: "v5.3.2", Semver: &semver.Version{Major: 5, Minor: 3, Patch: 2, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0119",
		DevOnly:            false,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0120": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0120",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "840b233e8d7917d5e601fd85a7a78a784a487c05",
			Label:  "dev-master#840b233",
			Semver: nil,
		},
		Link:               "https://example.com/support-docs/vendor/pkg-0120",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0121": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0121",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1", Label: "2.1.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0122": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0122",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0122",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0123": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0123",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1", Label: "4.0.1", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0123",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0124": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0124",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0124",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0125": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0125",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1-beta.2", Label: "2.2.1-beta.2", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: "-beta.2"}},
		Link:               "https://example.com/support-source/vendor/pkg-0125",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0126": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0126",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v2.2.0", Label: "v2.2.0", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0126",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0127": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0127",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0127",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0128": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0128",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &semver.Version{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0128",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0129": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0129",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0129",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0130": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0130",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "b1ab687038b06de2b5b8c572d76307fb7dc1354a",
			Label:  "1.2-dev#b1ab687",
			Semver: nil,
		},
		Link:               "https://example.com/support-docs/vendor/pkg-0130",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0131": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0131",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0131",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0132": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0132",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0133": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0133",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v4.1.1", Label: "v4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0133",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0134": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0134",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0134",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0135": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0135",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.0.1-beta.0", Label: "4.0.1-beta.0", Semver: &semver.Version{Major: 4, Minor: 0, Patch: 1, Extra: "-beta.0"}},
		Link:               "https://example.com/support-source/vendor/pkg-0135",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0136": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0136",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0136",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0137": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0137",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0137",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0138": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0138",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &semver.Version{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0138",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0139": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0139",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "4.1.1", Label: "4.1.1", Semver: &semver.Version{Major: 4, Minor: 1, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0139",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0140": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0140",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "882e270be9da8bec0be5c347ebe1e9a634723b4f",
			Label:  "dev-master#882e270",
			Semver: nil,
		},
		Link:               "https://example.com/support-docs/vendor/pkg-0140",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0141": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0141",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.0.1", Label: "2.0.1", Semver: &semver.Version{Major: 2, Minor: 0, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0141",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0142": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0142",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &semver.Version{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0142",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0143": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0143",
		Abandoned:          true,
		Version:            contract.PkgVersion{Raw: "4.2.1", Label: "4.2.1", Semver: &semver.Version{Major: 4, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0144": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0144",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.0.0", Label: "1.0.0", Semver: &semver.Version{Major: 1, Minor: 0, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0144",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0145": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0145",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.1.1-beta.1", Label: "2.1.1-beta.1", Semver: &semver.Version{Major: 2, Minor: 1, Patch: 1, Extra: "-beta.1"}},
		Link:               "https://example.com/support-source/vendor/pkg-0145",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0146": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0146",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &semver.Version{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0146",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0147": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0147",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "v3.3.0", Label: "v3.3.0", Semver: &semver.Version{Major: 3, Minor: 3, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-docs/vendor/pkg-0147",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0148": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0148",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "1.1.0", Label: "1.1.0", Semver: &semver.Version{Major: 1, Minor: 1, Patch: 0, Extra: ""}},
		Link:               "https://example.com/support-source/vendor/pkg-0148",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0149": &difftesting.TestPkgWrapper{
		Name:               "vendor/pkg-0149",
		Abandoned:          false,
		Version:            contract.PkgVersion{Raw: "2.2.1", Label: "2.2.1", Semver: &semver.Version{Major: 2, Minor: 2, Patch: 1, Extra: ""}},
		Link:               "https://example.com/support-wiki/vendor/pkg-0149",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
	"vendor/pkg-0150": &difftesting.TestPkgWrapper{
		Name:      "vendor/pkg-0150",
		Abandoned: false,
		Version: contract.PkgVersion{
			Raw:    "bcfdbc84c28a5bd099476ce1fe0f4e1d2b0d873a",
			Label:  "dev-master#bcfdbc8",
			Semver: nil,
		},
		Link:               "https://example.com/support-docs/vendor/pkg-0150",
		DevOnly:            true,
		RootRequirement:    false,
		RootDevRequirement: false,
	},
}
